src/Andy.X.Portal/Models/Producers/ProducerDetailsViewModel.cs
using System;
using System.Collections.Generic;

namespace Andy.X.Portal.Models.Producers
{
    public class ProducerDetailsViewModel
    {
        public string Tenant { get; set; }
        public string Product { get; set; }
        public string Component { get; set; }
        public string Topic { get; set; }

        public long Id { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }

        public ProducerInstanceType InstanceType { get; set; }

        public List<string> PublicIpRange { get; set; }
        public List<string> PrivateIpRange { get; set; }


        public DateTimeOffset? UpdatedDate { get; set; }
        public DateTimeOffset CreatedDate { get; set; }

        public string UpdatedBy { get; set; }
        public string CreatedBy { get; set; }


        public ProducerDetailsViewModel()
        {
            InstanceType = ProducerInstanceType.Multiple;
        }
    }
    public enum ProducerInstanceType
    {
        Single,
        Multiple
    }
}

src/Andy.X.Portal/Models/Producers/ProducerListViewModel.cs
using System.Collections.Generic;

namespace Andy.X.Portal.Models.Producers
{
    public class ProducerListViewModel
    {
        public List<ProducerActivity> Producers { get; set; }
        public ProducerListViewModel()
        {
            Producers = new List<ProducerActivity>();
        }
    }

    public class ProducerActivity
    {
        public string Key { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public bool IsActive { get; set; }

        public int InstancesCount { get; set; }

        public string Tenant { get; set; }
        public string Product { get; set; }
        public string Component { get; set; }
        public string Topic { get; set; }
    }
}

src/Andy.X.Portal/Controllers/ProducersController.cs
using Andy.X.Portal.Services.Producers;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace Andy.X.Portal.Controllers
{
    public class ProducersController : Controller
    {
        private readonly ProducerService producerService;

        public ProducersController(ProducerService producerService)
        {
            this.producerService = producerService;
        }

        public IActionResult Index()
        {
            var user = new Models.User()
            {
                Password = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "Password").Value,
                Username = HttpContext.User.Identity.Name
            };
            return View(producerService.GetProducerListViewModel(user));
        }

        public IActionResult Details(string tenant, string product, string component, string topic, string id)
        {
            var user = new Models.User()
            {
                Password = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "Password").Value,
                Username = HttpContext.User.Identity.Name
            };
            return View(producerService.GetProducerDetailsViewModel(user, tenant, product, component, topic, id));
        }
    }
}

src/Andy.X.Portal/Views/Producers/Details.cshtml
@using Andy.X.Portal.Models.Producers
@model ProducerDetailsViewModel
@{
    ViewData["Title"] = @Model.Name;
}

<div class="container mt-5">


    <div class="page-header">
        <div class="row align-items-center">
            <div class="col-auto">
                <span class="avatar avatar-lg" style="">
                    <img src="~/assets/producer.png" width="64" height="64" alt="producer">
                </span>
            </div>
            <div class="col">
                <h1 class="page-title">@Model.Name</h1>
                <div class="page-subtitle">
                    <div class="row">
                        <div class="col-auto">
                            <a class="text-reset">@Model.Tenant / @Model.Product / @Model.Component / @Model.Topic</a>
                        </div>
                        <div class="col-auto text-success">
                            @Model.InstanceType.ToString().ToUpper()
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="row row-cards mt-2">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="header">Producer</div>
                    <div class="subheader">Overview</div>

                    <div class="mb-3 mt-3">
                        <label class="form-label">Producer Name</label>
                        <input type="text" class="form-control" name="example-text-input" disabled value="@Model.Name" placeholder="No Information">
                    </div>

                    <div class="mb-3 mt-3">
                        <label class="form-label">Location</label>
                        <input type="text" class="form-control" name="example-text-input" disabled value="@Model.Tenant / @Model.Product / @Model.Component / @Model.Name" placeholder="No Information">
                    </div>

                    <div class="mb-3 mt-3">
                        <label class="form-label">Instance Type</label>
                        <input type="text" class="form-control" name="example-text-input" disabled value="@Model.InstanceType.ToString()" placeholder="No Information">
                    </div>

                    <div class="mb-3 mt-3">
                        <label class="form-label">Public Ip Range</label>
                        <input type="text" class="form-control" name="example-text-input" disabled value="@string.Join(", ",Model.PublicIpRange) " placeholder="No Information">
                    </div>

                    <div class="mb-3 mt-3">
                        <label class="form-label">Private Ip Range</label>
                        <input type="text" class="form-control" name="example-text-input" disabled value="@string.Join(", ",Model.PrivateIpRange) " placeholder="No Information">
                    </div>

                    <div class="mb-3 mt-3">
                        <label class="form-label">Updated by</label>
                        <input type="text" class="form-control" name="example-text-input" disabled value="@Model.UpdatedBy" placeholder="No Information">
                    </div>

                    <div class="mb-3 mt-3">
                        <label class="form-label">Updated date</label>
                        <input type="text" class="form-control" name="example-text-input" disabled value="@Model.UpdatedDate" placeholder="No Information">
                    </div>

                    <div class="mb-3 mt-3">
                        <label class="form-label">Created by</label>
                        <input type="text" class="form-control" name="example-text-input" disabled value="@Model.CreatedBy" placeholder="No Information">
                    </div>

                    <div class="mb-3 mt-3">
                        <label class="form-label">Created date</label>
                        <input type="text" class="form-control" name="example-text-input" disabled value="@Model.CreatedDate" placeholder="No Information">
                    </div>

                </div>
            </div>
        </div>
    </div>


</div>

src/Andy.X.Portal/Views/Producers/Index.cshtml
@using Andy.X.Portal.Models.Producers
@model ProducerListViewModel
@{
    ViewData["Title"] = "Data ingestion";
}

<div class="container mt-5">
    @if (Model.Producers.Count == 0)
    {
        <div class="alert alert-warning" role="alert">
            <center>There is no <strong>Data ingestion client</strong> connected at the moment!</center>
            <div class="text-muted"><center>To create a new producer, please use Andy X Cli or Andy X Clients.</center></div>
        </div>
    }
    else
    {
        <h1 class="page-title mt-5">Data ingestions</h1>
        <h5 class="">List</h5>
        <div class="row row-cards mt-1">

            @foreach (var producer in Model.Producers)
            {
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="row g-2 align-items-center">
                                <div class="col-auto">
                                    <span class="avatar avatar-lg" style="">
                                        <img src="./assets/producer.png" width="64" height="64" alt="producer">

                                    </span>
                                </div>
                                <div class="col">
                                    <div class="text-muted">
                                        Producer
                                    </div>
                                    <h4 class="card-title m-0">
                                        <a asp-controller="Producers" asp-action="Details" asp-route-tenant="@producer.Tenant" asp-route-product="@producer.Product" asp-route-component="@producer.Component" asp-route-topic="@producer.Topic" asp-route-id="@producer.Name">@producer.Name</a>
                                    </h4>
                                    <div class="text-muted">
                                        @producer.Location
                                    </div>
                                    @if (producer.IsActive)
                                    {
                                        <div class="small mt-1 col-auto">
                                            <span class="badge bg-green"></span> Online @producer.InstancesCount instances connected
                                        </div>
                                    }
                                    else
                                    {
                                        <div class="small mt-1 ">
                                            <span class="badge bg-danger"></span> Offline
                                        </div>
                                    }

                                </div>
                                <div class="col-auto">
                                    <a asp-controller="Producers" asp-action="Details" asp-route-tenant="@producer.Tenant" asp-route-product="@producer.Product" asp-route-component="@producer.Component" asp-route-topic="@producer.Topic" asp-route-id="@producer.Name" class="btn">
                                        View
                                    </a>
                                </div>
                                <div class="col-auto">
                                    <div class="dropdown">
                                        <a href="#" class="card-dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                                            <!-- Download SVG icon from http://tabler-icons.io/i/dots-vertical -->
                                            <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none" /><circle cx="12" cy="12" r="1" /><circle cx="12" cy="19" r="1" /><circle cx="12" cy="5" r="1" /></svg>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    }
</div>